import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AutoThemeWrapper } from "@/app/ui/AutoThemeWrapper";
import "@/app/ui/global.css";
import { Provider } from "jotai";
import { ErrorBoundary } from "react-error-boundary";
import { ErrorFallback } from "@/app/ui/ErrorFallback";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Provider>
          <AutoThemeWrapper>{children}</AutoThemeWrapper>
        </Provider>
      </body>
    </html>
  );
}
