import styles from "./layout.module.scss";
import { Sidebar } from "@/app/ui/Sidebar";
import { Header } from "@/app/ui/Header";
import { Flex } from "@radix-ui/themes";
import { ErrorBoundary } from "react-error-boundary";
import { ErrorFallback } from "@/app/ui/ErrorFallback";
import { SidebarProvider } from "@/app/ui/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.container}>
      <ErrorBoundary FallbackComponent={ErrorFallback}>
        <SidebarProvider>
          <Sidebar items={[]} />
        </SidebarProvider>
        <Flex direction="column" flexGrow="1">
          {/* // TODO: The user setting is tentative. */}
          <Header user={undefined} />
          <main className={styles.mainContent}>{children}</main>
        </Flex>
      </ErrorBoundary>
    </div>
  );
}
