import styles from "./layout.module.scss";
import { Flex } from "@radix-ui/themes";
import { Metadata } from "next";
import { Header } from "@/app/_ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GuestLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <div className={styles.container}>
      <Flex direction="column" flexGrow="1">
        <Header user={undefined} />
        <main className={styles.mainContent}>{children}</main>
      </Flex>
    </div>
  );
}
