import styles from "./layout.module.scss";
import { SidebarWrapper } from "./SidebarWrapper";
import { Header } from "@/app/ui/Header";
import { Flex } from "@radix-ui/themes";
import { Metadata } from "next";
import { auth } from "@/auth";
import { getMenuItemsByUserId } from "@/db/userMenuItemRelations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  const user = session?.user;
  const items = user?.id ? await getMenuItemsByUserId(user?.id) : [];

  return (
    <div className={styles.container}>
      <SidebarWrapper items={items || []} />
      <Flex direction="column" flexGrow="1">
        <Header user={user} />
        <main className={styles.mainContent}>{children}</main>
      </Flex>
    </div>
  );
}
